<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>one.year.senior</groupId>
    <artifactId>ecommerce-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>ecommerce-core</module>
        <module>ecommerce-api</module>
        <module>ecommerce-admin</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

<!--    Đây là khái niệm quan trọng nhất cần phân biệt:-->
<!--    <dependencies> (Trong Parent):-->
<!--    Nếu bạn khai báo thư viện ở đây, TẤT CẢ module con sẽ tự động bị ép phải tải thư viện về, dù chúng có cần hay không.-->
<!--    Dùng cho: Các thư viện cốt lõi như lombok, slf4j.-->

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

<!--    <dependencyManagement> (Trong Parent/BOM):-->
<!--    Khai báo ở đây CHƯA tải thư viện về. Nó chỉ định nghĩa phiên bản.-->
<!--    Module con muốn dùng thì phải khai báo lại trong <dependencies> của chính nó (nhưng không cần ghi version).-->
<!--    Dùng cho: Hầu hết các thư viện (Spring Security, Database drivers, Utils...).-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.2.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>one.year.senior</groupId>
                <artifactId>ecommerce-core</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>